import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { HeatMapProvider } from "@/components/HeatMapProvider";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "MEEPS",
  description: "Generated by create next app",
};


export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-linear-to-br from-black to-blue-500 h-screen`}
      >
        <HeatMapProvider>
          {children}
        </HeatMapProvider>
      </body>
    </html>
  );
}
